### ISSUE TITLE
New DSP Trigger bug

### ISSUE THREAD

**Issue by sagitta42** [legend-exp/LegendGeSim.jl#40]
@fhagemann  I got an error `MethodError: no method matching +(::Nothing, ::Int64)` at

https://github.com/legend-exp/LegendGeSim.jl/blob/3332d183f02a9d073e7d3d7a7eac2c554a44d8dc/src/trigger.jl#L86

I guess that's the no-trigger case? Before merging I tested with testdata, now this came up with g4simple hdf5 sim file. I would assume there are no non-triggering pulses in the testdata

**Comment by fhagemann** [comment]
Yes, that is when `findfirst` finds nothing. 
What would you like to return as `t0idx` then?

**Comment by sagitta42** [comment]
If it doesn't trigger i.e. finds nothing, the trigger index returned should be zero.

It is then passed to `simulate()` for the next stage which is "DAQ" simulation

https://github.com/legend-exp/LegendGeSim.jl/blob/3332d183f02a9d073e7d3d7a7eac2c554a44d8dc/src/pss_to_raw.jl#L142

where it's checked that if it's zero, we save a waveform that's just all zeros

https://github.com/legend-exp/LegendGeSim.jl/blob/3332d183f02a9d073e7d3d7a7eac2c554a44d8dc/src/daq.jl#L67

So

1) Could be zero in case of no-trigger to leave the rest of the code untouched
2) Could be `nothing` and change the check for trigger index to be for `nothing` which is probably more meaningful than zero actually
3) Why are we even saving non-triggered waveforms by "converting" them to all-flat zero wfs? I guess to preserve the "truth" info about each event, so that we could even check what happened to the ones that didn't trigger

**Comment by fhagemann** [comment]
PR #41 should provide exactly the case 1: returning zero in the case of no-trigger

**Comment by fhagemann** [comment]
> where it's checked that if it's zero, we save a waveform that's just all zeros
> 
> https://github.com/legend-exp/LegendGeSim.jl/blob/3332d183f02a9d073e7d3d7a7eac2c554a44d8dc/src/daq.jl#L67

To me it looks like we are creating a vector with undefined numbers (`similar`), not zeros
https://github.com/legend-exp/LegendGeSim.jl/blob/3332d183f02a9d073e7d3d7a7eac2c554a44d8dc/src/daq.jl#L69

This can result in crazy waveforms
